json.extract! car,
              :id,
              :label,
              :brand,
              :model_safe,
              :license_plate,
              :year,
              :color,
              :milage,
              :fuel,
              :transmission,
              :list_price,
              :created_at,
              :updated_at
json.url car_url(car, format: :json)
